# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user_response.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'user_response.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import pb.user_pb2 as user__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13user_response.proto\x12\x0cUserResponse\x1a\nuser.proto\"=\n\x0cResponseMeta\x12\x0c\n\x04page\x18\x01 \x02(\x05\x12\r\n\x05total\x18\x02 \x02(\x05\x12\x10\n\x08pageSize\x18\x03 \x02(\x05\"S\n\x0cUserResponse\x12\x19\n\x05users\x18\x01 \x03(\x0b\x32\n.user.User\x12(\n\x04meta\x18\x02 \x02(\x0b\x32\x1a.UserResponse.ResponseMeta')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_response_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESPONSEMETA']._serialized_start=49
  _globals['_RESPONSEMETA']._serialized_end=110
  _globals['_USERRESPONSE']._serialized_start=112
  _globals['_USERRESPONSE']._serialized_end=195
# @@protoc_insertion_point(module_scope)
