# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'user_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import pb.user_pb2 as user__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12user_service.proto\x12\x0buserService\x1a\nuser.proto\"\x1d\n\x0fUserRequestById\x12\n\n\x02id\x18\x01 \x02(\x03\"!\n\x11UserRequestByName\x12\x0c\n\x04name\x18\x01 \x02(\t\"(\n\x0cUserResponse\x12\x18\n\x04user\x18\x01 \x01(\x0b\x32\n.user.User2\x82\x02\n\nUserGetter\x12H\n\x0bGetUserById\x12\x1c.userService.UserRequestById\x1a\x19.userService.UserResponse\"\x00\x12L\n\rGetUserByName\x12\x1e.userService.UserRequestByName\x1a\x19.userService.UserResponse\"\x00\x12\\\n\x1bGetAllUsersMatchingUsername\x12\x1e.userService.UserRequestByName\x1a\x19.userService.UserResponse\"\x00\x30\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERREQUESTBYID']._serialized_start=47
  _globals['_USERREQUESTBYID']._serialized_end=76
  _globals['_USERREQUESTBYNAME']._serialized_start=78
  _globals['_USERREQUESTBYNAME']._serialized_end=111
  _globals['_USERRESPONSE']._serialized_start=113
  _globals['_USERRESPONSE']._serialized_end=153
  _globals['_USERGETTER']._serialized_start=156
  _globals['_USERGETTER']._serialized_end=414
# @@protoc_insertion_point(module_scope)
